import { BusinessMetricsService } from '../../src/observability/metrics/business-metrics.service';

export function createBusinessMetricsMock(): jest.Mocked<BusinessMetricsService> {
  return {
    recordHttpRequest: jest.fn(),
    recordRideCreated: jest.fn(),
    recordRideCompleted: jest.fn(),
    recordDeliveryCreated: jest.fn(),
    recordDeliveryCompleted: jest.fn(),
    recordPaymentConfirmed: jest.fn(),
    recordPaymentRefunded: jest.fn(),
    recordCashoutRequested: jest.fn(),
    recordCashoutApproved: jest.fn(),
    recordCashoutRejected: jest.fn(),
    recordPayoutCompleted: jest.fn(),
    recordPayoutFailed: jest.fn(),
    recordDispatchOfferCreated: jest.fn(),
    recordDispatchOfferAccepted: jest.fn(),
    recordDispatchMatchRun: jest.fn(),
    recordWebhookEvent: jest.fn(),
    recordWebhookRetryAttempt: jest.fn(),
    recordDomainEvent: jest.fn(),
    recordAuditLog: jest.fn(),
    recordOperationsAlert: jest.fn(),
    recordOperationsIntervention: jest.fn(),
    recordProviderRequest: jest.fn(),
    recordQueueJob: jest.fn(),
    recordWalletMovement: jest.fn(),
    setDriversOnline: jest.fn(),
    setActiveServices: jest.fn(),
    setPendingCashouts: jest.fn(),
    setFailedWebhooks: jest.fn(),
    setOutboxBacklog: jest.fn(),
  } as unknown as jest.Mocked<BusinessMetricsService>;
}
