export enum DispatchUnitStatus {
  OFFLINE = 'OFFLINE',
  AVAILABLE = 'AVAILABLE',
  OFFERED = 'OFFERED',
  RESERVED = 'RESERVED',
  EN_ROUTE_PICKUP = 'EN_ROUTE_PICKUP',
  WAITING = 'WAITING',
  ON_TRIP = 'ON_TRIP',
  ON_DELIVERY_ROUTE = 'ON_DELIVERY_ROUTE',
  CHARGING = 'CHARGING',
  BREAK_REQUIRED = 'BREAK_REQUIRED',
  DOCUMENT_BLOCKED = 'DOCUMENT_BLOCKED',
  SUSPENDED = 'SUSPENDED',
}

export enum UniversalServiceFamily {
  PASSENGER = 'PASSENGER',
  DELIVERY = 'DELIVERY',
  SPECIAL = 'SPECIAL',
}

export enum UniversalServiceType {
  STANDARD_RIDE = 'STANDARD_RIDE',
  EV_SCOOTER_RIDE = 'EV_SCOOTER_RIDE',
  EV_MOTORCYCLE_RIDE = 'EV_MOTORCYCLE_RIDE',
  BICYCLE_RIDE = 'BICYCLE_RIDE',
  MINI_CAR_RIDE = 'MINI_CAR_RIDE',
  PREMIUM_RIDE = 'PREMIUM_RIDE',
  PRIVATE_DRIVER = 'PRIVATE_DRIVER',
  BUSINESS_RIDE = 'BUSINESS_RIDE',
  AIRPORT_TRANSFER = 'AIRPORT_TRANSFER',
  INTERCITY = 'INTERCITY',
  TOURISM_EVENT = 'TOURISM_EVENT',
  NIGHTLIFE = 'NIGHTLIFE',
  SENIOR_ASSISTANCE = 'SENIOR_ASSISTANCE',
  MEDICAL_PWD_RIDE = 'MEDICAL_PWD_RIDE',
  AMBULANCE_TRANSPORT = 'AMBULANCE_TRANSPORT',
  SCHOOL_RIDE = 'SCHOOL_RIDE',
  RENTAL_WITH_DRIVER = 'RENTAL_WITH_DRIVER',
  SHARED_RIDE = 'SHARED_RIDE',
  PARCEL_BIKE = 'PARCEL_BIKE',
  PARCEL_SCOOTER = 'PARCEL_SCOOTER',
  PARCEL_CAR = 'PARCEL_CAR',
  COURIER = 'COURIER',
  FOOD_DELIVERY = 'FOOD_DELIVERY',
  CARGO_VAN = 'CARGO_VAN',
  CARGO_TRUCK = 'CARGO_TRUCK',
  MULTI_STOP_ROUTE = 'MULTI_STOP_ROUTE',
  PARTNER_VEHICLE = 'PARTNER_VEHICLE',
  FLEET_CONTRACT = 'FLEET_CONTRACT',
  SCHEDULED_ROSTER = 'SCHEDULED_ROSTER',
}

export enum UniversalScheduleType {
  IMMEDIATE = 'IMMEDIATE',
  SCHEDULED = 'SCHEDULED',
  RECURRING = 'RECURRING',
}

export enum UniversalRequestStatus {
  CREATED = 'CREATED',
  SCHEDULED = 'SCHEDULED',
  SEARCHING = 'SEARCHING',
  OFFERING = 'OFFERING',
  ASSIGNED = 'ASSIGNED',
  DRIVER_EN_ROUTE = 'DRIVER_EN_ROUTE',
  ARRIVED = 'ARRIVED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_QUALIFIED_DRIVER = 'NO_QUALIFIED_DRIVER',
  EXPIRED = 'EXPIRED',
}

export enum UniversalOfferStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  LOST_RACE = 'LOST_RACE',
}

export enum UniversalAssignmentStatus {
  ACTIVE = 'ACTIVE',
  RELEASED = 'RELEASED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum UniversalTripStatus {
  ASSIGNED = 'ASSIGNED',
  DRIVER_EN_ROUTE_PICKUP = 'DRIVER_EN_ROUTE_PICKUP',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  WAITING_FOR_RIDER = 'WAITING_FOR_RIDER',
  RIDER_VERIFIED = 'RIDER_VERIFIED',
  TRIP_STARTED = 'TRIP_STARTED',
  STOP_ARRIVED = 'STOP_ARRIVED',
  STOP_COMPLETED = 'STOP_COMPLETED',
  PACKAGE_QR_VERIFIED = 'PACKAGE_QR_VERIFIED',
  PACKAGE_PICKED_UP = 'PACKAGE_PICKED_UP',
  EN_ROUTE_DELIVERY = 'EN_ROUTE_DELIVERY',
  DELIVERY_ARRIVED = 'DELIVERY_ARRIVED',
  RECIPIENT_VERIFIED = 'RECIPIENT_VERIFIED',
  PACKAGE_DELIVERED = 'PACKAGE_DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  FAILED = 'FAILED',
}

export enum UniversalStopStatus {
  PENDING = 'PENDING',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}

export enum UniversalTripStopType {
  PICKUP = 'PICKUP',
  STOP = 'STOP',
  DROPOFF = 'DROPOFF',
  RETURN = 'RETURN',
  DELIVERY_PICKUP = 'DELIVERY_PICKUP',
  DELIVERY_DROPOFF = 'DELIVERY_DROPOFF',
}

export enum DispatchPolicyStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  RETIRED = 'RETIRED',
}

export enum DecisionOutcome {
  ELIGIBLE = 'ELIGIBLE',
  INELIGIBLE = 'INELIGIBLE',
  RANKED = 'RANKED',
  OFFERED = 'OFFERED',
  ASSIGNED = 'ASSIGNED',
  NO_QUALIFIED_DRIVER = 'NO_QUALIFIED_DRIVER',
  CANCELLED = 'CANCELLED',
  SHADOW = 'SHADOW',
  FAILED = 'FAILED',
}

export enum UniversalOutboxStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum DispatchOwnerType {
  INDIVIDUAL = 'INDIVIDUAL',
  FLEET = 'FLEET',
  PARTNER = 'PARTNER',
}

export enum DispatchShiftStatus {
  SCHEDULED = 'SCHEDULED',
  OPEN = 'OPEN',
  PAUSED = 'PAUSED',
  BREAK_REQUIRED = 'BREAK_REQUIRED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum DispatchQualificationStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum DispatchCancellationParty {
  RIDER = 'RIDER',
  DRIVER = 'DRIVER',
  AGENT = 'AGENT',
  DISPATCHER = 'DISPATCHER',
  FLEET = 'FLEET',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum DispatchExclusionType {
  USER_BLOCK = 'USER_BLOCK',
  DRIVER_CHANGE = 'DRIVER_CHANGE',
  SAFETY = 'SAFETY',
  TEMPORARY = 'TEMPORARY',
}

export enum DispatchReasonCode {
  DRIVER_INACTIVE = 'DRIVER_INACTIVE',
  DRIVER_UNVERIFIED = 'DRIVER_UNVERIFIED',
  DRIVER_UNSAFE = 'DRIVER_UNSAFE',
  DRIVER_SUSPENDED = 'DRIVER_SUSPENDED',
  SERVICE_NOT_ENTITLED = 'SERVICE_NOT_ENTITLED',
  CERTIFICATION_MISSING = 'CERTIFICATION_MISSING',
  CERTIFICATION_EXPIRED = 'CERTIFICATION_EXPIRED',
  ACTIVE_VEHICLE_MISSING = 'ACTIVE_VEHICLE_MISSING',
  VEHICLE_INACTIVE = 'VEHICLE_INACTIVE',
  VEHICLE_UNVERIFIED = 'VEHICLE_UNVERIFIED',
  VEHICLE_CLASS_NOT_ALLOWED = 'VEHICLE_CLASS_NOT_ALLOWED',
  CAPACITY_INSUFFICIENT = 'CAPACITY_INSUFFICIENT',
  CARGO_WEIGHT_EXCEEDED = 'CARGO_WEIGHT_EXCEEDED',
  CARGO_VOLUME_EXCEEDED = 'CARGO_VOLUME_EXCEEDED',
  CAPABILITY_MISSING = 'CAPABILITY_MISSING',
  DOCUMENT_INVALID = 'DOCUMENT_INVALID',
  INSURANCE_INVALID = 'INSURANCE_INVALID',
  INSPECTION_INVALID = 'INSPECTION_INVALID',
  REGISTRATION_INVALID = 'REGISTRATION_INVALID',
  LOCATION_MISSING = 'LOCATION_MISSING',
  LOCATION_STALE = 'LOCATION_STALE',
  LOCATION_INACCURATE = 'LOCATION_INACCURATE',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
  ASSIGNMENT_CONFLICT = 'ASSIGNMENT_CONFLICT',
  OFFER_CONFLICT = 'OFFER_CONFLICT',
  OPERATING_ZONE_RESTRICTED = 'OPERATING_ZONE_RESTRICTED',
  RIDER_DRIVER_EXCLUDED = 'RIDER_DRIVER_EXCLUDED',
  SHIFT_INACTIVE = 'SHIFT_INACTIVE',
  SHIFT_TIME_INSUFFICIENT = 'SHIFT_TIME_INSUFFICIENT',
  SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT',
  TIME_WINDOW_INFEASIBLE = 'TIME_WINDOW_INFEASIBLE',
  ROUTE_INFEASIBLE = 'ROUTE_INFEASIBLE',
  EV_RANGE_INSUFFICIENT = 'EV_RANGE_INSUFFICIENT',
  CHARGING_IN_PROGRESS = 'CHARGING_IN_PROGRESS',
  SHARED_INSERTION_INFEASIBLE = 'SHARED_INSERTION_INFEASIBLE',
  FLEET_RESTRICTION = 'FLEET_RESTRICTION',
  PAYMENT_NOT_AUTHORIZED = 'PAYMENT_NOT_AUTHORIZED',
  SCHOOL_ROSTER_UNAUTHORIZED = 'SCHOOL_ROSTER_UNAUTHORIZED',
}

export const TERMINAL_REQUEST_STATUSES = new Set<UniversalRequestStatus>([
  UniversalRequestStatus.COMPLETED,
  UniversalRequestStatus.CANCELLED,
  UniversalRequestStatus.NO_QUALIFIED_DRIVER,
  UniversalRequestStatus.EXPIRED,
]);

export const ACTIVE_ASSIGNMENT_STATUSES = new Set<UniversalAssignmentStatus>([
  UniversalAssignmentStatus.ACTIVE,
]);
