export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  RIDER = 'RIDER',
  DRIVER = 'DRIVER',
  FLEET_MANAGER = 'FLEET_MANAGER',
  FLEET_PARTNER = 'FLEET_PARTNER',
  AGENT = 'AGENT',
  DISPATCHER = 'DISPATCHER',
  TOUR_OPERATOR = 'TOUR_OPERATOR',
  RENTAL_PARTNER = 'RENTAL_PARTNER',
  MEDICAL_PARTNER = 'MEDICAL_PARTNER',
  SUPPORT = 'SUPPORT',
  ADMIN = 'ADMIN',
}

export enum AccountStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
}

export enum ServiceType {
  RIDE = 'RIDE',
  DELIVERY = 'DELIVERY',
  TOURIST_VEHICLE = 'TOURIST_VEHICLE',
  AMBULANCE = 'AMBULANCE',
  CAR_RENTAL = 'CAR_RENTAL',
  SCHOOL_SHUTTLE = 'SCHOOL_SHUTTLE',
}

export enum BookingStatus {
  DRAFT = 'DRAFT',
  QUOTED = 'QUOTED',
  REQUESTED = 'REQUESTED',
  SEARCHING = 'SEARCHING',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  DRIVER_EN_ROUTE = 'DRIVER_EN_ROUTE',
  ARRIVED = 'ARRIVED',
  WAITING = 'WAITING',
  VERIFIED = 'VERIFIED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  NO_SHOW = 'NO_SHOW',
}

export enum DeliveryStatus {
  CREATED = 'CREATED',
  WAITING_ACCEPTANCE = 'WAITING_ACCEPTANCE',
  ACCEPTED = 'ACCEPTED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  EN_ROUTE_PICKUP = 'EN_ROUTE_PICKUP',
  ARRIVED_PICKUP = 'ARRIVED_PICKUP',
  PICKED_UP = 'PICKED_UP',
  QR_VERIFIED = 'QR_VERIFIED',
  IN_TRANSIT = 'IN_TRANSIT',
  ARRIVED_DROPOFF = 'ARRIVED_DROPOFF',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum DeliveryRouteStatus {
  DRAFT = 'DRAFT',
  PLANNED = 'PLANNED',
  DISPATCHED = 'DISPATCHED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TripPauseStatus {
  REQUESTED = 'REQUESTED',
  PAUSED = 'PAUSED',
  REJECTED = 'REJECTED',
  RESUMED = 'RESUMED',
  CANCELLED = 'CANCELLED',
}

export enum PushPlatform {
  EXPO = 'EXPO',
  FCM = 'FCM',
  APNS = 'APNS',
  WEB = 'WEB',
}

export enum MatchingJobStatus {
  QUEUED = 'QUEUED',
  DISPATCHING = 'DISPATCHING',
  WAITING = 'WAITING',
  ASSIGNED = 'ASSIGNED',
  EXHAUSTED = 'EXHAUSTED',
  CANCELLED = 'CANCELLED',
}

export enum LedgerAccountType {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  REVENUE = 'REVENUE',
  EXPENSE = 'EXPENSE',
  EQUITY = 'EQUITY',
}

export enum JournalStatus {
  PENDING = 'PENDING',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
}

export enum DomainEventStatus {
  PENDING = 'PENDING',
  PUBLISHED = 'PUBLISHED',
  FALLBACK = 'FALLBACK',
  FAILED = 'FAILED',
}

export enum PushDeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum RentalStatus {
  REQUESTED = 'REQUESTED',
  CONFIRMED = 'CONFIRMED',
  PICKUP_INSPECTION = 'PICKUP_INSPECTION',
  ACTIVE = 'ACTIVE',
  RETURN_INSPECTION = 'RETURN_INSPECTION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum DriverVerificationStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum DriverAvailabilityStatus {
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE',
  BUSY = 'BUSY',
  PAUSED = 'PAUSED',
}

export enum DocumentStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_REVIEW = 'IN_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum DocumentType {
  NATIONAL_ID = 'NATIONAL_ID',
  DRIVING_LICENSE_FRONT = 'DRIVING_LICENSE_FRONT',
  DRIVING_LICENSE_BACK = 'DRIVING_LICENSE_BACK',
  WORK_PERMIT = 'WORK_PERMIT',
  GOOD_CONDUCT = 'GOOD_CONDUCT',
  MEDICAL_REPORT = 'MEDICAL_REPORT',
  DRIVER_PHOTO = 'DRIVER_PHOTO',
  VEHICLE_LOGBOOK = 'VEHICLE_LOGBOOK',
  VEHICLE_INSURANCE = 'VEHICLE_INSURANCE',
  VEHICLE_INSPECTION = 'VEHICLE_INSPECTION',
  ROAD_LICENSE = 'ROAD_LICENSE',
  AMBULANCE_CERTIFICATION = 'AMBULANCE_CERTIFICATION',
  OTHER = 'OTHER',
}

export enum VehicleStatus {
  DRAFT = 'DRAFT',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  REJECTED = 'REJECTED',
}

export enum VehicleType {
  BICYCLE = 'BICYCLE',
  SCOOTER = 'SCOOTER',
  MOTORCYCLE = 'MOTORCYCLE',
  MINI_CAR = 'MINI_CAR',
  SEDAN = 'SEDAN',
  HATCHBACK = 'HATCHBACK',
  CROSSOVER = 'CROSSOVER',
  SUV = 'SUV',
  MINIVAN = 'MINIVAN',
  VAN = 'VAN',
  TRUCK = 'TRUCK',
  LUXURY = 'LUXURY',
  BUS = 'BUS',
  AMBULANCE = 'AMBULANCE',
}

export enum EnergyType {
  ELECTRIC = 'ELECTRIC',
  HYBRID = 'HYBRID',
  INTERNAL_COMBUSTION = 'INTERNAL_COMBUSTION',
}

export enum RideMode {
  ON_DEMAND = 'ON_DEMAND',
  SCHEDULED = 'SCHEDULED',
  SHARED = 'SHARED',
  INTERCITY = 'INTERCITY',
}

export enum RideCategory {
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  SENIOR_ASSISTANCE = 'SENIOR_ASSISTANCE',
  MEDICAL_PWD_TRANSFER = 'MEDICAL_PWD_TRANSFER',
  AIRPORT_TRANSFER = 'AIRPORT_TRANSFER',
  EVENT = 'EVENT',
  SCHOOL = 'SCHOOL',
  BUSINESS = 'BUSINESS',
}

export enum TripType {
  ONE_WAY = 'ONE_WAY',
  ROUND_TRIP = 'ROUND_TRIP',
  MULTI_STOP = 'MULTI_STOP',
}

export enum StopType {
  PICKUP = 'PICKUP',
  STOP = 'STOP',
  DROPOFF = 'DROPOFF',
  RETURN = 'RETURN',
}

export enum StopStatus {
  PENDING = 'PENDING',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}

export enum OfferStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REVERSED = 'REVERSED',
}

export enum CashoutRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  EVZONE_WALLET = 'EVZONE_WALLET',
  CARD = 'CARD',
  MOBILE_MONEY = 'MOBILE_MONEY',
  BANK_TRANSFER = 'BANK_TRANSFER',
  INSURANCE = 'INSURANCE',
  CORPORATE_PAY = 'CORPORATE_PAY',
}

export enum WalletTransactionType {
  TOP_UP = 'TOP_UP',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  TRANSFER = 'TRANSFER',
  PAYOUT = 'PAYOUT',
  TIP = 'TIP',
  ADJUSTMENT = 'ADJUSTMENT',
  EARNING = 'EARNING',
  CASHOUT_RESERVE = 'CASHOUT_RESERVE',
  CASHOUT_RELEASE = 'CASHOUT_RELEASE',
}

export enum TransactionDirection {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum DeliveryServiceType {
  BIKE = 'BIKE',
  ELECTRIC_VEHICLE = 'ELECTRIC_VEHICLE',
  TRUCK = 'TRUCK',
  COURIER = 'COURIER',
  FOOD = 'FOOD',
}

export enum PackageSize {
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
  CUSTOM = 'CUSTOM',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED',
}

export enum EmergencyPriority {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum EmergencyType {
  MEDICAL = 'MEDICAL',
  ACCIDENT = 'ACCIDENT',
  FIRE = 'FIRE',
  NATURAL_DISASTER = 'NATURAL_DISASTER',
  SECURITY = 'SECURITY',
  OTHER = 'OTHER',
}

export enum EmergencyStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESPONDING = 'RESPONDING',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  SYSTEM = 'SYSTEM',
  BOOKING = 'BOOKING',
  PAYMENT = 'PAYMENT',
  DRIVER = 'DRIVER',
  DELIVERY = 'DELIVERY',
  SAFETY = 'SAFETY',
  PROMOTION = 'PROMOTION',
  DOCUMENT = 'DOCUMENT',
  CHAT = 'CHAT',
}

export enum SupportTicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_USER = 'WAITING_USER',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum SupportPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum InspectionType {
  PICKUP = 'PICKUP',
  RETURN = 'RETURN',
}

export enum TrainingProgressStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
}

export enum OrganizationType {
  CORPORATE_CLIENT = 'CORPORATE_CLIENT',
  FLEET_PARTNER = 'FLEET_PARTNER',
  AGENT_DISPATCH = 'AGENT_DISPATCH',
  SCHOOL_OPERATOR = 'SCHOOL_OPERATOR',
  MEDICAL_PROVIDER = 'MEDICAL_PROVIDER',
  TOUR_OPERATOR = 'TOUR_OPERATOR',
  RENTAL_OPERATOR = 'RENTAL_OPERATOR',
}

export enum OrganizationStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}

export enum OrganizationMemberRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  FLEET_MANAGER = 'FLEET_MANAGER',
  DISPATCH_MANAGER = 'DISPATCH_MANAGER',
  DISPATCHER = 'DISPATCHER',
  AGENT = 'AGENT',
  FINANCE = 'FINANCE',
  COMPLIANCE = 'COMPLIANCE',
  VIEWER = 'VIEWER',
}

export enum MembershipStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
}

export enum FleetAssetStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
}

export enum FleetAssignmentStatus {
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MaintenanceStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum BookingSource {
  RIDER_APP = 'RIDER_APP',
  DRIVER_APP = 'DRIVER_APP',
  AGENT = 'AGENT',
  DISPATCHER = 'DISPATCHER',
  FLEET_PARTNER = 'FLEET_PARTNER',
  ADMIN = 'ADMIN',
  API = 'API',
  SCHOOL_APP = 'SCHOOL_APP',
  CORPORATE_PAY = 'CORPORATE_PAY',
}

export enum ManualBookingStatus {
  DRAFT = 'DRAFT',
  CREATED = 'CREATED',
  DISPATCH_PENDING = 'DISPATCH_PENDING',
  ASSIGNED = 'ASSIGNED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum DispatchPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
  EMERGENCY = 'EMERGENCY',
}

export enum DispatchAssignmentStatus {
  PENDING = 'PENDING',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum IntegrationStatus {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTED = 'CONNECTED',
  DEGRADED = 'DEGRADED',
  ERROR = 'ERROR',
  SUSPENDED = 'SUSPENDED',
}

export enum SyncDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
  BIDIRECTIONAL = 'BIDIRECTIONAL',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
}

export enum CorporatePayTransactionStatus {
  CREATED = 'CREATED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  AUTHORIZED = 'AUTHORIZED',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  DECLINED = 'DECLINED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum CorporatePayRequestKind {
  QUOTE = 'QUOTE',
  SERVICE_BOOKING = 'SERVICE_BOOKING',
  RIDE_SCHEDULE = 'RIDE_SCHEDULE',
  DELIVERY = 'DELIVERY',
  RFQ = 'RFQ',
  REBOOKING = 'REBOOKING',
}

export enum CorporatePayRequestStatus {
  DRAFT = 'DRAFT',
  QUOTED = 'QUOTED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  AUTHORIZED = 'AUTHORIZED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DECLINED = 'DECLINED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REFUNDED = 'REFUNDED',
  DISPUTED = 'DISPUTED',
}

export enum CorporatePayAuthorizationStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  AUTHORIZED = 'AUTHORIZED',
  DECLINED = 'DECLINED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
  CONSUMED = 'CONSUMED',
}

export enum CorporatePayDisputeStatus {
  OPEN = 'OPEN',
  IN_REVIEW = 'IN_REVIEW',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

export enum CorporatePayEvidenceType {
  TRIP_RECEIPT = 'TRIP_RECEIPT',
  COMPLETION_LOG = 'COMPLETION_LOG',
  DELIVERY_CONFIRMATION = 'DELIVERY_CONFIRMATION',
  SIGNATURE = 'SIGNATURE',
  PHOTO = 'PHOTO',
  INVOICE = 'INVOICE',
  OTHER = 'OTHER',
}

export enum ReconciliationStatus {
  OPEN = 'OPEN',
  MATCHED = 'MATCHED',
  MISMATCHED = 'MISMATCHED',
  RESOLVED = 'RESOLVED',
  IGNORED = 'IGNORED',
}

export enum WebhookEventStatus {
  RECEIVED = 'RECEIVED',
  VERIFIED = 'VERIFIED',
  PROCESSED = 'PROCESSED',
  DUPLICATE = 'DUPLICATE',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}
